export const profiles = [
   {
      id: 'eJv0K4UaoXpPHutvQxZW',
      active: true,
      name: 'Raj',
      surname: 'Singh',
      email: 'raj.singh@gmail.com',
      gender: 'Male',
      maritalStatus: 'Widowed',
      religion: 'Sikh',
      caste: 'Jat',
      gothram: 'Sandhu',
      complexion: 'Fair',
      kujaDosam: 'No',
      motherTongue: 'Punjabi',
      physicalStatus: 'Normal',
      dateOfBirth: '1985-09-18',
      height: '6\' 0"',
      placeOfBirth: 'Amritsar',
      timeOfBirth: '1:45 PM',
      fatherName: 'Harbhajan Singh',
      fatherOccupation: 'Farmer',
      motherName: 'Jaspreet Kaur',
      motherOccupation: 'Homemaker',
      brothers: 3,
      sisters: 2,
      citizenOf: 'India',
      nativeState: 'Punjab',
      nativeCity: 'Amritsar',
      residingCountry: 'India',
      residingState: 'Punjab',
      residingCity: 'Amritsar',
      completeAddress: 'Lawrence Road, Amritsar',
      contactNo: '7654321098',
      aboutFamily: 'Raj comes from a close-knit and traditional Sikh family...',
      nakshatram: 'Uttarabhadra',
      raasi: 'Meena',
      padam: '2nd',
      educationCategory: 'Science',
      educationDetails: 'M.Sc',
      occupationCategory: 'Government Employee',
      occupationDetails: 'Professor',
      annualIncome: 'INR 14,00,000 per annum',
      aboutMe: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
      ageDifference: 5,
      partnerHeight: '5\' 5"',
      partnerNakshatram: 'Anuradha',
      partnerRaasi: 'Vrischika',
      partnerGothram: 'Sandhu',
      partnerKujaDosam: 'No',
      partnerComplexion: 'Fair',
      partnerMotherTongue: 'Punjabi',
      partnerReligion: 'Sikh',
      partnerCaste: 'Jat',
      partnerPhysicalStatus: 'Normal',
      partnerEducationCategory: 'Science',
      partnerEducationDetails: 'Ph.D',
      partnerOccupationCategory: 'Private Employee',
      partnerOccupationDetails: 'IT Consultant',
      partnerCitizenOf: 'India',
      partnerNativeState: 'Punjab',
      partnerNativeCity: 'Amritsar',
      partnerResidingCountry: 'India',
      partnerResidingState: 'Punjab',
      partnerResidingCity: 'Amritsar',
      aboutPartner: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
      images: [
         'https://cdn2.momjunction.com/wp-content/uploads/2021/02/What-Is-A-Sigma-Male-And-Their-Common-Personality-Trait-624x702.jpg'
      ],
      createdAt: {
         seconds: 1703616660,
         nanoseconds: 897000000
      },
      createdAtOriginal: {
         seconds: 1703616660,
         nanoseconds: 929000000
      }
   },
   {
      id: 'I2cdRzqoj52nDkrBAzw0',
      active: true,
      name: 'Rahul',
      surname: 'Mehta',
      email: 'rahul.mehta@gmail.com',
      gender: 'Male',
      maritalStatus: 'Single',
      religion: 'Jain',
      caste: 'Digambar',
      gothram: 'Kashyap',
      complexion: 'Wheatish',
      kujaDosam: 'No',
      motherTongue: 'Gujarati',
      physicalStatus: 'Normal',
      dateOfBirth: '1992-08-20',
      height: '5\' 9"',
      placeOfBirth: 'Ahmedabad',
      timeOfBirth: '4:45 PM',
      fatherName: 'Sanjay Mehta',
      fatherOccupation: 'Businessman',
      motherName: 'Smita Mehta',
      motherOccupation: 'Homemaker',
      brothers: 1,
      sisters: 0,
      citizenOf: 'India',
      nativeState: 'Gujarat',
      nativeCity: 'Ahmedabad',
      residingCountry: 'India',
      residingState: 'Gujarat',
      residingCity: 'Ahmedabad',
      completeAddress: 'Vastrapur, Ahmedabad',
      contactNo: '7654321098',
      aboutFamily: 'Rahul belongs to a well-established and traditional family...',
      nakshatram: 'Shravana',
      raasi: 'Makara',
      padam: '1st',
      educationCategory: 'Commerce',
      educationDetails: 'MBA',
      occupationCategory: 'Private Employee',
      occupationDetails: 'Finance Analyst',
      annualIncome: 'INR 15,00,000 per annum',
      aboutMe: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit Lorem ipsum dolor sit amet, consectetur adipiscing elit',
      ageDifference: 1,
      partnerHeight: '5\' 5"',
      partnerNakshatram: 'Uttara Bhadrapada',
      partnerRaasi: 'Meena',
      partnerGothram: 'Bharadwaj',
      partnerKujaDosam: 'No',
      partnerComplexion: 'Fair',
      partnerMotherTongue: 'Gujarati',
      partnerReligion: 'Jain',
      partnerCaste: 'Digambar',
      partnerPhysicalStatus: 'Normal',
      partnerEducationCategory: 'Commerce',
      partnerEducationDetails: 'CA',
      partnerOccupationCategory: 'Private Employee',
      partnerOccupationDetails: 'Marketing Professional',
      partnerCitizenOf: 'India',
      partnerNativeState: 'Gujarat',
      partnerNativeCity: 'Ahmedabad',
      partnerResidingCountry: 'India',
      partnerResidingState: 'Gujarat',
      partnerResidingCity: 'Ahmedabad',
      aboutPartner: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
      images: [
         'https://t3.ftcdn.net/jpg/06/11/89/42/360_F_611894278_6sIqAi9Akdrw9aNulK77WHPJJHJFWTV0.jpg'
      ],
      createdAt: {
         seconds: 1703703180,
         nanoseconds: 210000000
      },
      createdAtOriginal: {
         seconds: 1703616660,
         nanoseconds: 810000000
      }
   },
   {
      id: '6iU43Ivc39iqjcLzbMYS',
      active: true,
      name: 'Ayesha',
      surname: 'Khan',
      email: 'ayesha.khan@gmail.com',
      gender: 'Female',
      maritalStatus: 'Divorced',
      religion: 'Islam',
      caste: 'Sunni',
      gothram: 'Not Applicable',
      complexion: 'Olive',
      kujaDosam: 'No',
      motherTongue: 'Urdu',
      physicalStatus: 'Normal',
      dateOfBirth: '1988-04-05',
      height: '5\' 6"',
      placeOfBirth: 'Mumbai',
      timeOfBirth: '8:15 AM',
      fatherName: 'Ismail Khan',
      fatherOccupation: 'Engineer',
      motherName: 'Farida Khan',
      motherOccupation: 'Teacher',
      brothers: 2,
      sisters: 1,
      citizenOf: 'India',
      nativeState: 'Maharashtra',
      nativeCity: 'Mumbai',
      residingCountry: 'India',
      residingState: 'Maharashtra',
      residingCity: 'Mumbai',
      completeAddress: 'Andheri West, Mumbai',
      contactNo: '9876543210',
      aboutFamily: 'Ayesha comes from a loving and supportive family...',
      nakshatram: 'Revati',
      raasi: 'Meena',
      padam: '3rd',
      educationCategory: 'Arts',
      educationDetails: 'MA in Literature',
      occupationCategory: 'Government Employee',
      occupationDetails: 'Public Relations Officer',
      annualIncome: 'INR 8,00,000 per annum',
      aboutMe: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit Lorem ipsum dolor sit amet, consectetur adipiscing elit',
      ageDifference: 4,
      partnerHeight: '5\' 8"',
      partnerNakshatram: 'Hasta',
      partnerRaasi: 'Kanya',
      partnerGothram: 'Not Applicable',
      partnerKujaDosam: 'No',
      partnerComplexion: 'Wheatish',
      partnerMotherTongue: 'Urdu',
      partnerReligion: 'Islam',
      partnerCaste: 'Sunni',
      partnerPhysicalStatus: 'Normal',
      partnerEducationCategory: 'Engineering & MCA (BE/B.Tech/M.tech/MCA)',
      partnerEducationDetails: 'BE',
      partnerOccupationCategory: 'Private Employee',
      partnerOccupationDetails: 'Software Developer',
      partnerCitizenOf: 'India',
      partnerNativeState: 'Maharashtra',
      partnerNativeCity: 'Mumbai',
      partnerResidingCountry: 'India',
      partnerResidingState: 'Maharashtra',
      partnerResidingCity: 'Mumbai',
      aboutPartner: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
      images: [
         'https://img.freepik.com/free-photo/woman-doing-close-up-photoshoot-studio_53876-14476.jpg'
      ],
      createdAt: {
         seconds: 1703703060,
         nanoseconds: 21000000
      },
      createdAtOriginal: {
         seconds: 1703616660,
         nanoseconds: 678000000
      }
   },
   {
      id: 'QaDnNs3fLhAEzdxomumC',
      active: true,
      name: 'Priya',
      surname: 'Sharma',
      email: 'priya.sharma@gmail.com',
      gender: 'Female',
      maritalStatus: 'Single',
      religion: 'Hindu',
      caste: 'Brahmin',
      gothram: 'Bharadwaj',
      complexion: 'Wheatish',
      kujaDosam: 'No',
      motherTongue: 'Hindi',
      physicalStatus: 'Normal',
      dateOfBirth: '1990-05-15',
      height: '5\' 5"',
      placeOfBirth: 'Delhi',
      timeOfBirth: '2:30 PM',
      fatherName: 'Rakesh Sharma',
      fatherOccupation: 'Doctor',
      motherName: 'Sunita Sharma',
      motherOccupation: 'Professor',
      brothers: 2,
      sisters: 1,
      citizenOf: 'India',
      nativeState: 'Uttar Pradesh',
      nativeCity: 'Lucknow',
      residingCountry: 'India',
      residingState: 'Delhi',
      residingCity: 'New Delhi',
      completeAddress: 'Saket, New Delhi',
      contactNo: '9876543210',
      aboutFamily: 'Priya comes from a well-educated and close-knit family...',
      nakshatram: 'Rohini',
      raasi: 'Vrishabha',
      padam: '2nd',
      educationCategory: 'Medical',
      educationDetails: 'MBBS',
      occupationCategory: 'Government Employee',
      occupationDetails: 'Civil Servant',
      annualIncome: 'INR 10,00,000 per annum',
      aboutMe: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...Lorem ipsum dolor sit amet, consectetur adipiscing elit',
      ageDifference: 2,
      partnerHeight: '5\' 8"',
      partnerNakshatram: 'Swati',
      partnerRaasi: 'Tula',
      partnerGothram: 'Kashyap',
      partnerKujaDosam: 'No',
      partnerComplexion: 'Fair',
      partnerMotherTongue: 'Hindi',
      partnerReligion: 'Hindu',
      partnerCaste: 'Brahmin',
      partnerPhysicalStatus: 'Normal',
      partnerEducationCategory: 'Medical',
      partnerEducationDetails: 'MD',
      partnerOccupationCategory: 'Private Employee',
      partnerOccupationDetails: 'Software Engineer',
      partnerCitizenOf: 'India',
      partnerNativeState: 'Uttar Pradesh',
      partnerNativeCity: 'Lucknow',
      partnerResidingCountry: 'India',
      partnerResidingState: 'Delhi',
      partnerResidingCity: 'New Delhi',
      aboutPartner: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
      images: [
         'https://img.freepik.com/free-photo/pretty-smiling-joyfully-female-with-fair-hair-dressed-casually-looking-with-satisfaction_176420-15187.jpg?size=626&ext=jpg&ga=GA1.1.1546980028.1703635200&semt=ais'
      ],
      createdAt: {
         seconds: 1703703060,
         nanoseconds: 888000000
      },
      createdAtOriginal: {
         seconds: 1703616660,
         nanoseconds: 611000000
      }
   },
   {
      id: '7I3xxEMVHu3UKdbrYFMe',
      active: true,
      name: 'Ankur',
      surname: 'Joshi',
      email: 'ankur.joshi@gmail.com',
      gender: 'Male',
      maritalStatus: 'Unmarried',
      religion: 'Hindu',
      caste: 'Kshatriya',
      gothram: 'Vashishta',
      complexion: 'Fair',
      kujaDosam: 'No',
      motherTongue: 'Marathi',
      physicalStatus: 'Normal',
      dateOfBirth: '1993-12-10',
      height: '5\' 11"',
      placeOfBirth: 'Pune',
      timeOfBirth: '10:00 AM',
      fatherName: 'Rajendra Joshi',
      fatherOccupation: 'Businessman',
      motherName: 'Anita Joshi',
      motherOccupation: 'Homemaker',
      brothers: 0,
      sisters: 1,
      citizenOf: 'India',
      nativeState: 'Maharashtra',
      nativeCity: 'Pune',
      residingCountry: 'India',
      residingState: 'Maharashtra',
      residingCity: 'Pune',
      completeAddress: 'Koregaon Park, Pune',
      contactNo: '8765432109',
      aboutFamily: 'Ankur belongs to a traditional yet open-minded family...',
      nakshatram: 'Pushya',
      raasi: 'Karka',
      padam: '4th',
      educationCategory: 'Engineering & MCA (BE/B.Tech/M.tech/MCA)',
      educationDetails: 'M.Tech',
      occupationCategory: 'Private Employee',
      occupationDetails: 'Civil Engineer',
      annualIncome: 'INR 12,00,000 per annum',
      aboutMe: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
      ageDifference: 3,
      partnerHeight: '6\' 0"',
      partnerNakshatram: 'Pushya',
      partnerRaasi: 'Karka',
      partnerGothram: 'Vashishta',
      partnerKujaDosam: 'No',
      partnerComplexion: 'Fair',
      partnerMotherTongue: 'Marathi',
      partnerReligion: 'Hindu',
      partnerCaste: 'Kshatriya',
      partnerPhysicalStatus: 'Normal',
      partnerEducationCategory: 'Engineering & MCA (BE/B.Tech/M.tech/MCA)',
      partnerEducationDetails: 'M.Tech',
      partnerOccupationCategory: 'Private Employee',
      partnerOccupationDetails: 'Civil Engineer',
      partnerCitizenOf: 'India',
      partnerNativeState: 'Maharashtra',
      partnerNativeCity: 'Pune',
      partnerResidingCountry: 'India',
      partnerResidingState: 'Maharashtra',
      partnerResidingCity: 'Pune',
      aboutPartner: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
      images: [
         'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?cs=srgb&dl=pexels-italo-melo-2379004.jpg&fm=jpg'
      ],
      createdAt: {
         seconds: 1703703137,
         nanoseconds: 997000000
      },
      createdAtOriginal: {
         seconds: 1703616077,
         nanoseconds: 699000000
      }
   }
]

export const succesMaches = [
   {
      maleName: "Ramcharan",
      femaleName: "Manasvi",
      imgUrl:
         "https://st4.depositphotos.com/18241762/20336/i/450/depositphotos_203360210-stock-photo-happiness.jpg",
      date: "11 Dec, 2022",
   },
   {
      maleName: "Rahul",
      femaleName: "Priya",
      imgUrl:
         "https://media.istockphoto.com/id/1306446747/photo/happy-romantic-young-couple-falling-in-love.jpg?s=612x612&w=0&k=20&c=3fBZAaoHNA1cRNT2klkJ7GwoYlplXZue4znrhXmvfXM=",
      date: "11 Dec, 2020",
   },
   {
      maleName: "Prabhas",
      femaleName: "Anusha",
      imgUrl:
         "https://st4.depositphotos.com/18241762/20336/i/450/depositphotos_203360210-stock-photo-happiness.jpg",
      date: "11 Jan, 2021",
   },
]
